### ISSUE TITLE
Add lists of NIME reviewers for all years

### ISSUE THREAD

**Issue by cpmpercussion** [NIME-conference/nime-website#10]
Some people have requested lists of reviewers for the various conferences. I think this would be a good thing to have, and have now managed to dig out all years except for 2004 and 2013 (have asked Michael Lyons to see if he can dig in his archive for these)
https://docs.google.com/spreadsheets/d/1PskDy-uAz1orDNWTfT9fMPoW_gOEW8TR4f9zb_1aGIs/edit?usp=sharing

Do you have a good solution for how to present this on the web page? We could just make one very long list, that would suffice for "proving" that people have reviewed. But if you can come up with a smarter/nicer presentation style, that would be great!

**Comment by alexarje** [comment]
Text files with all reviewers are now listed [here](https://github.com/NIME-conference/NIME-bibliography/tree/master/reviewers). Just need to make a smart way of presenting them on the web page.

**Comment by alexarje** [comment]
Have added a simple list [here](https://www.nime.org/archives/reviewers/) now. Could probably be fancier, but works for now.
