### ISSUE TITLE
Create an intro page for the forum

### ISSUE THREAD

**Issue by disastrid** [NIME-conference/nime-website#20]
It's likely that people will find the NIME forum before they know about the NIME community. Therefore, I'm working on a page that briefly summarises what NIME is, where it comes from, and how to participate.

**Comment by alexarje** [comment]
Great, yes, this is a very good point!

**Comment by cpmpercussion** [comment]
there's a default "Welcome to the NIME forum!" topic which you could edit as needed for this purpose if you want: https://forum.nime.org/t/welcome-to-the-nime-forum/
