### ISSUE TITLE
Fix menu

### ISSUE THREAD

**Issue by alexarje** [NIME-conference/nime-website#23]
I see that the menu is now breaking into two lines: 

![Screenshot from 2020-09-15 10-15-56](https://user-images.githubusercontent.com/114316/93184420-859d5300-f73c-11ea-982a-1b1c58e6f35d.png)

It would be nice to add drop-down menus to allow for having more menu elements in a structured manner.

**Comment by cpmpercussion** [comment]
fixed by making the text size smaller.
