### ISSUE TITLE
Some of the Abstract and BibTex buttons in the proceedings page are not working

### ISSUE THREAD

**Issue by dimitriaatos** [NIME-conference/nime-website#28]
Search for example for `10.5281/zenodo.1176342` in the [proceedings page](https://www.nime.org/archives/) and try viewing the abstract or the BibTeX of the paper, nothing happens and the following error is printed to the console (chrome).
```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '.collapse.jtilbian:2017a-abstract' is not a valid selector.
```
It seems that the colon (`:`) in the class name causes the problem. If I'm not mistaken, the class names of each paper are generated from the citation key of the paper, that is found in the [`_bibliography/nime_papers.bib`](https://github.com/NIME-conference/nime-website/blob/master/_bibliography/nime_papers.bib) file. I found 23 citation keys that contain a colon, which means 23 broken Abstract and BibTex buttons in the proceedings page.

I guess it'll be safe to pass all citation keys through a function that removes the colon, before using them for class names.

**Comment by alexarje** [comment]
Thanks for finding this bug. What do you think, @cpmpercussion? The easiest may be to remove the colons from the citation keys. But a more robust solution is to change the code? Or we can do both...

**Comment by cpmpercussion** [comment]
Thanks for finding this! I've eliminated colons over in the bib repo and migrated them over here.
