### ISSUE TITLE
Change proceedings datasource away from BibTex

### ISSUE THREAD

**Issue by cpmpercussion** [NIME-conference/nime-website#29]
BibTex is a fine datasource for latex documents, but it has some issues for our website.

We currently use the [Jekyll scholar plugin](https://github.com/inukshuk/jekyll-scholar) to parse the bibtex files and create  nice lists of all the papers, pieces, installations etc.

Jekyll scholar should be able to create individual pages for each bibtex entry but in practice this is too slow (we have >1800 papers in the NIME proceedings archive). I haven't been able to successfully build the site with individual paper pages.

Anecdotally, time efficiency can be an issue with Jekyll plugins. Jekyll-scholar isn't designed for a very large number of entries whereas Jekyll itself can be efficient with (e.g.) large numbers of blog posts.

Jekyll [supports several data formats](https://jekyllrb.com/docs/datafiles/) (e.g., JSON, YAML, CSV) natively.

It might make more sense to export the bibtex to JSON and have Jekyll handle it by other means rather than persist with the  bibtex file.

Just a thought bubble right now, but could be a future project.

**Comment by alexarje** [comment]
Yes, good point. The nice thing about the BibTeX is that it can easily be edited and exported/imported in various tools. But perhaps we could have a flow where the nime20*.bib files are converted to a common JSON for further processing?

**Comment by cpmpercussion** [comment]
yep, that's what I meant I guess. It's straightforward to convert from Bibtex to JSON (or something else) in python and it could be part of the collate bibtex scripts over in the bib repo.
