### ISSUE TITLE
Errors in 2023 proceedings

### ISSUE THREAD

**Issue by stefanofasciani** [NIME-conference/nime-website#46]
In the recently published 2023 proceedings (https://nime.org/archives/) there are several papers with strange characters in the title or authors (the bibtex file instead seems to be ok).

I am not sure if that page is generated automatically or if that was a human error, but it seems some bad conversion from non-ASCII characters in the paper/author name. The wrong entries are (there may be more):

Anna-Kaisa Kaila, Petra JÃ¤Ã¤skelÃ¤inen, and Andre Holzapfel. 2023. Ethically Aligned Stakeholder Elicitation (EASE): Case Study in Music-AI. Proceedings of the International Conference on New Interfaces for Musical Expression. DOI:

Claudio Panariello, and Chiara Percivati. 2023. [â€œWYPYMâ€: A Study for Feedback-Augmented Bass Clarinet. ](https://nime.org/proc/nime2023_24/index.html)Proceedings of the International

Notto J. W. Thelle, and Bernt Isak WÃ¦rstad. 2023. [Co-Creatives Spaces: The machine as a collaborator. ](https://nime.org/proc/nime2023_35/index.html)Proceedings of the International Conference on New Interfaces for Musical Expression. DOI:

ThÃ©o Jourdan, and Baptiste Caramiaux. 2023. [Machine Learning for Musical Expression: A Systematic Literature Review. ](https://nime.org/proc/nime2023_46/index.html)Proceedings of the International Conference on New Interfaces for Musical Expression. DOI:

ThÃ©o Jourdan, and Baptiste Caramiaux. 2023. [Culture and Politics of Machine Learning in NIME: A Preliminary Qualitative Inquiry. ](https://nime.org/proc/nime2023_47/index.html)Proceedings of the International Conference on New Interfaces for Musical Expression. DOI:

MichaÅ‚ Seta, Dirk J Stromberg, and D STEWART . 2023. Building hybrid performances with DMIs, Hubs and Faust. Proceedings of the International Conference on New Interfaces for Musical Expression. DOI:

Erin M Gee. 2023. The BioSynthâ€”an affective biofeedback device grounded in feminist thought. Proceedings of the International Conference on New Interfaces for Musical Expression. DOI:

Hugh A von Arnim, Stefano Fasciani, and Ã‡aÄŸrÄ± Erdem . 2023. The Feedback Mop Cello: An Instrument for Interacting with Acoustic Feedback Loops. Proceedings of the International Conference on New Interfaces for Musical Expression. DOI:

**Comment by stefanofasciani** [comment]
I have noticed that this issue affect also proceedings of previous years (scrolling down I found similar errors in 2014 and 2015).

**Comment by cpmpercussion** [comment]
this was actually an issue across the whole site and was due to problems with the theme (didn't set the content type or charset in meta tags).

I didn't notice before until I changed the web host (and webserver) for the site on Monday. It should work now 👍
