### ISSUE TITLE
File nime2023_95.pdf missing

### ISSUE THREAD

**Issue by stefanofasciani** [NIME-conference/nime-website#49]
The PDF of this paper https://nime.org/proc/nime2023_95/ is not available from its PDF Link https://nime.org/proceedings/2023/nime2023_95.pdf.

It appears that the file is missing (the paper can be found here https://sebastianlobbers.com/static/9324af8a968715544e88586037601b98/SketchSynth_Lobbers_NIME.pdf)

**Comment by cpmpercussion** [comment]
I don't know how, but that file ended up with incorrect permissions on the server.

Good catch and it's fixed now, I don't see any other incorrect permissions within the proceedings.
