### ISSUE TITLE
Individual pages for each paper

### ISSUE THREAD

**Issue by cpmpercussion** [NIME-conference/nime-website#6]

**Comment by alexarje** [comment]
Something like what they are doing for WAC could be relevant, see, for example [this post](https://webaudioconf.com/posts/2019_12/). They are also using BibTeX files as the basis for the repository I think, so we could check with them.

**Comment by cpmpercussion** [comment]
I _thought_ that I couldn't get this to work, but just found I had a typo 🙃 .

Pushing a prototype idea now.

**Comment by cpmpercussion** [comment]
finally it built! building all the detail files takes 180s!

well it sort of works now, but isn't styled or linked anywhere. The layout file is `bibtex.html` in the `_layouts` directory, might change this filename later.
